### ISSUE TITLE
Shortcodes don't work correctly with enabled Markdown Extra

### ISSUE THREAD

**Issue by wolkyura** [getgrav/grav-plugin-shortcode-core#108]
Hello!

I'm using the `latest` version of Grav and have the next settings in `system.yaml`:

```
absolute_urls: false

home:
  alias: '/home'

pages:
  theme: custom
  markdown:
    extra: true
  process:
    markdown: true
    twig: false

cache:
  enabled: true
  check:
    method: file
  driver: auto
  prefix: 'g'

twig:
  cache: true
  debug: true
  auto_reload: true
  autoescape: false

assets:
  css_pipeline: false
  css_minify: true
  css_rewrite: true
  js_pipeline: false
  js_minify: true

errors:
  display: true
  log: true

debugger:
  enabled: false
  twig: true
  shutdown:
    close_connection: true
gpm:
  releases: stable
  verify_peer: true
```

I noticed one problem with shortcodes - when you have them in one line with content, e.g.:
`[div]Content[/div]`

Result:
`<p></p>`

But when I use shortcode in this way:

```
[div]
Content
[/div]
```

Everything works correctly

### Notes
- the problem is disappeared when you set the next settings in `system.yaml`:
```
pages:
  theme: custom
  markdown:
    extra: false
```

or
```
pages:
  theme: custom
  markdown:
    extra: true
  process:
    markdown: false
    twig: false
```
