### ISSUE TITLE
Shortcode breaks LangSwitcher

### ISSUE THREAD

**Issue by martinec** [getgrav/grav-plugin-shortcode-core#11]
Hello,

I'm trying to use the Shortcode Core plugin v2.0.2, but when it is enabled it seems like breaks the LangSwitcher v1.1.0 plugin, specifically the variable langswitcher.current becomes empty if it is inside a modular page template. Maybe I am missing something here? Please help me understand. Thanks!

Here is some minimal sample code to reproduce the issue:
##### config/system.yaml

```
languages:
  supported:
    - en
    - el
    - fr

cache:
  enabled: false

twig:
  cache: false
```
##### config/plugins/langswitcher.yaml

```
enabled: true
built_in_css: false
```
##### config/plugins/shortcode-core.yaml

```
enabled: true
active: false
active_admin: false
parser: wordpress
load_fontawesome: false
```
##### pages/01.home/modular.en.md

```

---
title: 'Foo'
menu: Home
onpage_menu: true
content:
    items: @self.modular
    order:
        by: default
        dir: asc
        custom:
            - _header

---
```
##### pages/01.home/_header/header.md

```

---
title: Home

---
```
##### templates/modular.html.twig

```
{% extends 'partials/base.html.twig' %}
...
{% block content %}
    {{ page.content }}
    {% for module in page.collection() %}
        {{ module.content }}
    {% endfor %}
{% endblock %}
...
```
##### templates/partials/base.html.twig

```
<!DOCTYPE html>
...
<head>
  ...
</head>
<body>
  {% block nav %}
      {% set lang = langswitcher.current %}
      <!-- this works ok output is <span>---en---</span> -->
      <span>---{{lang}}---</span>
  {% endblock %}
  {% block body %}
    {% block content %}{% endblock %}
  {% endblock %}
  ...
</body>
</html>
```
##### templates/modular/header.html.twig

```
templates/modular/header.html.twig
      {% set lang = langswitcher.current %}
      <!-- this does not work output is <span>------</span> -->
      <span>---{{lang}}---</span>
```

When shortcode-core is enabled, `header.html.twig` produces:
`<span>------</span>`

If it is disabled, the output is:
`<span>---en---</span>`
