### ISSUE TITLE
Latest Update 4.0.1 Breaks FontAwesome

### ISSUE THREAD

**Issue by HarDX** [getgrav/grav-plugin-shortcode-core#66]
Latest Update 4.0.1 Breaks FontAwesome
I try use default config, change wordpress/regexp, reinstall plugin - not helped, when downgrade to 3.0.1 all is ok.

**Comment by rhukster** [comment]
![Image 2019-04-03 at 9 49 52 AM](https://user-images.githubusercontent.com/1084697/55493324-f3f85f00-55f5-11e9-8e3d-5ef47a6187bc.png)

Works fine for me with all 3 parsers.

**Comment by HarDX** [comment]
v5 enable or disable - default settings for plugin?

**Comment by rhukster** [comment]
Defaults.. as you gave me no specific settings.

**Comment by rhukster** [comment]
![Image 2019-04-03 at 11 46 02 AM](https://user-images.githubusercontent.com/1084697/55500712-13978380-5606-11e9-8652-bc3d8d4e17b7.png)

```
fontawesome:
  load: true
  url: '//use.fontawesome.com/releases/v5.8.1/css/all.css'
  v5: true
```
